In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

In [4]:
pd.set_option('display.width', 200)
pd.set_option('display.max_columns', 60)

In [14]:
ROOT = Path().cwd().parent 
ATTACK_ROOT = ROOT / "Attack" / "LiRA"
RESULTS = ATTACK_ROOT / "results"

data = pd.read_csv(RESULTS / "lira_comparison.csv")

In [13]:
display(data.head())

,model,variant,epsilon,n_runs,attack_auc,attack_auc_std,advantage,advantage_std,tpr_at_10pct,tpr_at_10pct_std,tpr_at_1pct,tpr_at_1pct_std,tpr_at_0p1pct,tpr_at_0p1pct_std,sd_in,sd_in_std,sd_out,sd_out_std,test_acc,test_acc_std,n_members,n_nonmembers,n_shadow_trained,online,balanced,dataset
0,SVM,standard,NaN,1,0.548115,0.0,0.065504,0.0,0.140417,0.0,0.020777,0.0,0.004403,0.0,0.211255,0.0,0.217552,0.0,0.747578,0.0,56553,14139,32,True,False,DIABETES
1,SVM,dp,0.1,1,0.504296,0.0,0.011567,0.0,0.100490,0.0,0.010698,0.0,0.001167,0.0,0.182701,0.0,0.182781,0.0,0.728199,0.0,56553,14139,32,True,False,DIABETES
2,SVM,dp,0.2,1,0.503493,0.0,0.009751,0.0,0.099252,0.0,0.009973,0.0,0.001061,0.0,0.092523,0.0,0.092573,0.0,0.726572,0.0,56553,14139,32,True,False,DIABETES
3,SVM,dp,0.4,1,0.502719,0.0,0.009794,0.0,0.099959,0.0,0.009796,0.0,0.000690,0.0,0.053866,0.0,0.053895,0.0,0.726289,0.0,56553,14139,32,True,False,DIABETES
4,SVM,dp,0.8,1,0.502522,0.0,0.009549,0.0,0.096547,0.0,0.009672,0.0,0.000619,0.0,0.039722,0.0,0.039732,0.0,0.725935,0.0,56553,14139,32,True,False,DIABETES

In [25]:
df = pd.read_csv(ROOT / "prereplication_backups" / "lira" / "lira_comparison.csv")

display(df[df["online"] == "False"].head())

Empty DataFrame
Columns: [model, variant, epsilon, n_runs, attack_auc, attack_auc_std, advantage, advantage_std, tpr_at_10pct, tpr_at_10pct_std, tpr_at_1pct, tpr_at_1pct_std, tpr_at_0p1pct, tpr_at_0p1pct_std, sd_in, sd_in_std, sd_out, sd_out_std, test_acc, test_acc_std, n_members, n_nonmembers, n_shadow_trained, online, balanced, dataset]
Index: []

In [23]:
print(df["model"].unique())
print(df["variant"].unique())

print(df[df["variant"] == "dp"]["n_runs"].unique())

<StringArray>
['LR', 'RF', 'GNB', 'SVM', 'DNN']
Length: 5, dtype: str
<StringArray>
['standard', 'dp']
Length: 2, dtype: str
[5 1]